spring.main.web-application-type=none
spring.profiles.active=giga

logging.level.root=INFO
logging.level.org.example=INFO
logging.level.dev.langchain4j.http.client.log=DEBUG
logging.level.chat.giga.http.client=DEBUG
#logging.level.ai.djl=TRACE
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.cloud.openfeign.okhttp.enabled=true

logging.level.org.example.client=DEBUG
spring.cloud.openfeign.client.config.default.loggerLevel=BASIC

#spring.cloud.config.enabled=false

auto.start=false
use.pause.detect=false
#
voice.folder=C:/Users/arylk/voice
face.detection=C:/Users/arylk/model/retinaface.pt
feature.extract=C:/Users/arylk/model/face_feature.pt
whisper.model=C:/Users/arylk/model/whisper_ru.zip
embedding.model=C:/Users/arylk/model/embeddingModel.onnx
embedding.model.tokenizer=C:/Users/arylk/model/tokenizer.json